src/Gstay/guesthostBundle/Entity/hostguest.php
<?php
/**
 * Created by PhpStorm.
 * User: USER
 * Date: 04/02/2017
 * Time: 21:28
 */

namespace Gstay\guesthostBundle\Entity;
use AppBundle\Entity;
use Doctrine\ORM\Mapping as ORM ;

use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity
 * @Vich\Uploadable
 */
class hostguest
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     */
    private $id ;

    /**
     * @ORM\Column(type="integer" , nullable=true)
     */
    private $cin;

    /**
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\User")
     * @ORM\JoinColumn(name="id_user", referencedColumnName="id")
     */
    private $id_user ;

    /**
     * @ORM\Column(type="string",length=255 , nullable=true)
     */
    private $FirstName;

    /**
     * @ORM\Column(type="string",length=255 , nullable=true)
     */
    private $LastName;

    /**
     * @ORM\Column(type="string",length=255 , nullable=true)
     */
    private $Email;

    /**
     * @ORM\Column(type="integer" , nullable=true)
     */
    private $numTel;

    /**
     * @ORM\Column(type="string",length=255 , nullable=true)
     */
    private $rue;

    /**
     * @ORM\Column(type="integer" , nullable=true)
     */
    private $codePostale;

    /**
     * @ORM\Column(type="string",length=255 , nullable=true)
     */
    private $Emploi;

    /**
     * @ORM\Column(type="string",length=255 , nullable=true)
     */

    private $Country;

    /**
     * @ORM\Column(type="string",length=255 , nullable=true)
     */

    private $Etat;

    /**
     * @ORM\Column(type="date",nullable=true)
     */
    private $dateInscrit;

    /**
     *@ORM\Column(type="string",length=255,options={"default" : "en attente"},nullable=true)
     */
    private $promo;
    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="imageName")
     *
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     *
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return hostguest
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param string $imageName
     *
     * @return hostguest
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getImageName()
    {
        return $this->imageName;
    }


    /**
     * @return mixed
     */
    public function getPromo()
    {
        return $this->promo;
    }

    /**
     * @param mixed $promo
     */
    public function setPromo($promo)
    {
        $this->promo = $promo;
    }



    /**
     * @return mixed
     */
    public function getCin()
    {
        return $this->cin;
    }

    /**
     * @param mixed $cin
     */
    public function setCin($cin)
    {
        $this->cin = $cin;
    }

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->FirstName;
    }

    /**
     * @param mixed $FirstName
     */
    public function setFirstName($FirstName)
    {
        $this->FirstName = $FirstName;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->LastName;
    }

    /**
     * @param mixed $LastName
     */
    public function setLastName($LastName)
    {
        $this->LastName = $LastName;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->Email;
    }

    /**
     * @param mixed $Email
     */
    public function setEmail($Email)
    {
        $this->Email = $Email;
    }

    /**
     * @return mixed
     */
    public function getNumTel()
    {
        return $this->numTel;
    }

    /**
     * @param mixed $numTel
     */
    public function setNumTel($numTel)
    {
        $this->numTel = $numTel;
    }

    /**
     * @return mixed
     */
    public function getRue()
    {
        return $this->rue;
    }

    /**
     * @param mixed $rue
     */
    public function setRue($rue)
    {
        $this->rue = $rue;
    }

    /**
     * @return mixed
     */
    public function getCodePostale()
    {
        return $this->codePostale;
    }

    /**
     * @param mixed $codePostale
     */
    public function setCodePostale($codePostale)
    {
        $this->codePostale = $codePostale;
    }

    /**
     * @return mixed
     */
    public function getEmploi()
    {
        return $this->Emploi;
    }

    /**
     * @param mixed $Emploi
     */
    public function setEmploi($Emploi)
    {
        $this->Emploi = $Emploi;
    }

    /**
     * @return mixed
     */
    public function getCountry()
    {
        return $this->Country;
    }

    /**
     * @param mixed $Country
     */
    public function setCountry($Country)
    {
        $this->Country = $Country;
    }

    /**
     * @return mixed
     */
    public function getEtat()
    {
        return $this->Etat;
    }

    /**
     * @param mixed $Etat
     */
    public function setEtat($Etat)
    {
        $this->Etat = $Etat;
    }

    /**
     * @return mixed
     */
    public function getIdUser()
    {
        return $this->id_user;
    }

    /**
     * @param mixed $id_user
     */
    public function setIdUser($id_user)
    {
        $this->id_user = $id_user;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getDateInscrit()
    {
        return $this->dateInscrit;
    }

    /**
     * @param mixed $dateInscrit
     */
    public function setDateInscrit($dateInscrit)
    {
        $this->dateInscrit = $dateInscrit;
    }


}

src/Gstay/guesthostBundle/Controller/LogementController.php
<?php
/**
 * Created by PhpStorm.
 * User: USER
 * Date: 06/02/2017
 * Time: 22:14
 */

namespace Gstay\guesthostBundle\Controller;



use Gstay\eventBundle\Entity\profile;
use Gstay\guesthostBundle\Form\EquipementType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Gstay\guesthostBundle\Entity\LogementPortfolio;
use Gstay\guesthostBundle\Entity\Logement;
use Gstay\guesthostBundle\Entity\hostguest;
use Symfony\Component\HttpFoundation\Request;
use Gstay\guesthostBundle\Entity\Equipement;
use Gstay\guesthostBundle\Form\LogementType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;


class LogementController extends Controller
{
    /**
 * @Route("/listlogement",name="listlogement")
 */
    public function listLogementAction(Request $request)
    {

        $em=$this->getDoctrine()->getManager();


        $logements=$em->getRepository('GstayguesthostBundle:Logement')->findAll();
        $paginator  = $this->get('knp_paginator');

        $result= $pagination = $paginator->paginate(
            $logements, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            $request->query->getInt('limit', 6)
        );


        return $this->render('GstayguesthostBundle:Logement:listlogement.html.twig',
            array('logements'=>$result));

    }


    /**
     * @Route("/logementDetail/{idlogement}",name="logementDetail")
     */
    public function logementDetailAction($idlogement)
    {
        $user = $this->getUser();
        if (!is_object($user) ) {

            return $this->redirectToRoute('fos_user_security_login');
        }
        $id =  $this->getUser()->getId();

        $em=$this->getDoctrine()->getManager();

        $profile = $em->getRepository('GstayguesthostBundle:hostguest')->findOneBy(array('id_user' => $id ));

        $logements = $em->getRepository('GstayguesthostBundle:Logement')->findOneBy(array('idlogement' => $idlogement ));
        $portfolio = $em->getRepository('GstayguesthostBundle:LogementPortfolio')->findBy(array('id_user' => $idlogement ));

        $equip = $em->getRepository('GstayguesthostBundle:Equipement')->findBy(array('idequiplogement' =>$idlogement  ));
        return $this->render('GstayguesthostBundle:Logement:logementdetails.html.twig',array("logements"=>$logements,
            "equi"=>$equip,"portfolio"=>$portfolio,'profile'=>$profile));

    }

    /**
     * @Route("/deleteLogement/{id}",name="deleteLogement")
     */
    public function deleteLogementAction($id)
    {
        $user = $this->getUser();
        if (!is_object($user) ) {

            return $this->redirectToRoute('fos_user_security_login');
        }



        $em=$this->getDoctrine()->getManager();
        $Logement = $em->getRepository('GstayguesthostBundle:Logement')->findOneBy(array('idlogement' => $id ));

        $em->remove($Logement);
        $em->flush();

        return $this->redirect($this->generateUrl('meslogements',array('msg'=>"Delete successful")));





    }
    /**
     * @Route("/deleteEquipement/{id}",name="deleteEquipement")
     */
    public function deleteEquipementAction($id)
    {
        $user = $this->getUser();
        if (!is_object($user) ) {

            return $this->redirectToRoute('fos_user_security_login');
        }



        $em=$this->getDoctrine()->getManager();

        $equip = $em->getRepository('GstayguesthostBundle:Equipement')->findOneBy(array('idequipement' => $id ));



            $em->remove($equip);
        $em->flush();
        return $this->redirectToRoute('editLogement',array('idlogement'=>1));






    }
    /**
     * @Route("/editLogement/{idlogement}",name="editLogement")
     */
    public function editLogementAction(Request $request,$idlogement)
    {
        $user = $this->getUser();
        if (!is_object($user) ) {

            return $this->redirectToRoute('fos_user_security_login');
        }
        $id =  $this->getUser()->getId();


        $em=$this->getDoctrine()->getManager();
        $profile = $em->getRepository('GstayguesthostBundle:hostguest')->findOneBy(array('id_user' => $id ));

        $equipement=new Equipement();

        $Logement = $em->getRepository('GstayguesthostBundle:Logement')->findOneBy(array('idlogement' => $idlogement));
        $equip = $em->getRepository('GstayguesthostBundle:Equipement')->findBy(array('idequiplogement' => $Logement ));
        $form = $this->createForm(LogementType::class,$Logement );
        $fForm = $this->createForm(EquipementType::class,$equipement );

        $form->handleRequest($request);
        $fForm->handleRequest($request);
        if($fForm->isSubmitted() ) {
        $equipement->setIdequiplogement($Logement);


            $em->persist($equipement);
            $em->flush();
            return $this->redirectToRoute('editLogement',array('idlogement'=>$idlogement));
//            return $this->redirect($this->generateUrl('editLogement',array('msg'=>"Edit successful")));
        }

        if($form->isSubmitted() ) {


            $em->persist($Logement);
            $em->flush();
            return $this->redirect($this->generateUrl('meslogements',array('msg'=>"Edit successful")));
        }
        return $this->render('GstayguesthostBundle:Logement:editLogement.html.twig',array(
            'form'=>$form->createView(),
            'fform'=>$fForm->createView(),
            'profile'=>$profile,
            'felicity'=>$equip,
            'a'=>$Logement
        ));




    }






    /**
     * @Route("/MesLogements",name="meslogements")
     */
    public function MesLogementsAction()
    {


        $user = $this->getUser();
        if (!is_object($user) ) {

            return $this->redirectToRoute('fos_user_security_login');
        }
        $id =  $this->getUser()->getId();


        $em=$this->getDoctrine()->getManager();
        $profile = $em->getRepository('GstayguesthostBundle:hostguest')->findOneBy(array('id_user' => $id ));

        $logement=$em->getRepository('GstayguesthostBundle:Logement')->findBy(array('idlogementuser'=>$profile));


        return $this->render('GstayguesthostBundle:Logement:mesLogements.html.twig',
            array('logements'=>$logement,'profile'=>$profile));



    }





        /**
         * @Route("/Equipement",name="Equipement")
         */
        public function EquimpeementAction(Request $request) {
        $user = $this->getUser();
        if (!is_object($user) ) {

            return $this->redirectToRoute('fos_user_security_login');
        }
        $id =  $this->getUser()->getId();

        $Equipement = new Equipement();
        $em=$this->getDoctrine()->getManager();
            $profile = $em->getRepository('GstayguesthostBundle:hostguest')->findOneBy(array('id_user' => $id ));

        $equip = $em->getRepository('GstayguesthostBundle:Equipement')->findBy(array('idequiplogement' => $id ));
        $form = $this->createForm(EquipementType::class,$Equipement );


        $form->handleRequest($request);

        if($form->isSubmitted() ) {
            $em->persist($Equipement);
            $em->flush();
            return $this->redirect($this->generateUrl('Equipement',array('msg'=>"add successful")));
        }
        return $this->render('GstayguesthostBundle:Logement:LogementEquipement.html.twig',array(
            'form'=>$form->createView(),
            'profile'=>$profile,
            'felicity'=>$equip,



        ));




    }

    /**
     * @Route("/addEquipement",name="addEquipement")
     */
     public function addEquipementAction(Request $request)
    {
        $user = $this->getUser();
        if (!is_object($user)) {

            return $this->redirectToRoute('fos_user_security_login');
        }
        $id = $this->getUser()->getId();

        $equipement = new Equipement();
        $em = $this->getDoctrine()->getManager();
        $profile = $em->getRepository('GstayguesthostBundle:hostguest')->findOneBy(array('id_user' => $id));


        $form = $this->createForm(EquipementType::class,$equipement);


        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            $equipement >setIdUser($user);
            $em->persist($equipement);
            $em->flush();
            return $this->redirect($this->generateUrl('addEquipement', array('msg' => "add successful")));
        }
        return $this->render('GstayguesthostBundle:Logement:editLogement.html.twig', array(
            'form' => $form->createView(),
            'profile' => $profile


        ));


    }






    /**
     * @Route("/listBookings/{idlogements}",name="listBookings")
     */
    /*
    public function listBookingsAction($idlogements)
    {

        $user = $this->getUser();
        if (!is_object($user) ) {

            return $this->redirectToRoute('fos_user_security_login');
        }
        $id =  $this->getUser()->getId();

        $em=$this->getDoctrine()->getManager();
        $profile = $em->getRepository('GstayguesthostBundle:hostguest')->findOneBy(array('id_user' => $id ));


        $logements = $em->getRepository('GstayguesthostBundle:Logement')->findOneBy(array('idlogement' => $idlogements ));

        return $this->render('GstayguesthostBundle:Logement:list.html.twig',array("logements"=>$logements,"profile"=>$profile));
    }


*/

    /**
     * @Route("/addlogements",name="addlogement")
     */
     public function addLogementAction(Request $request)
    {


        $user = $this->getUser();
        if (!is_object($user)) {

            return $this->redirectToRoute('fos_user_security_login');
        }
        $id = $this->getUser()->getId();

        $Logement = new Logement();
        $em = $this->getDoctrine()->getManager();
        $profile = $em->getRepository('GstayguesthostBundle:hostguest')->findOneBy(array('id_user' => $id));

        $form = $this->createForm(LogementType::class, $Logement  );


        $form->handleRequest($request);

src/Gstay/guesthostBundle/Resources/views/Logement/LogementEquipement.html.twig
{% extends 'base.html.twig' %}
{% block title %} Settings-Facilities {% endblock %}
{% block body %}



    <!-- Wrap -->
    <div id="wrap">


    <!--Banner-->
    <section class="sub-banner">
        <!--Background-->
        <div class="bg-parallax bg-1"></div>
        <!--End Background-->
        <!-- Logo -->
        <div class="logo-banner text-center">
            <a href="" title="">

                <img src="{{ asset('bundles/app/images/logo-banner.png') }}" alt="">
            </a>
        </div>
        <!-- Logo -->
    </section>
    <!--End Banner-->

    <!-- Main -->
    <div class="main">
        <div class="container">
            <div class="main-cn element-page bg-white clearfix">
                <!--Breakcrumb-->
                <section class="breakcrumb-sc">
                    <ul class="breadcrumb arrow">
                        <li><a href=""><i class="fa fa-home"></i></a></li>
                        <li>Add Event</li>
                    </ul>
                </section>
                <!--End Breakcrumb-->

                <section class="user-profile">
                    <div class="row">

                        <div class="col-md-3">
                            <div class="user-profile__header">
                                <h4>{{ profile.firstName }}_{{ profile.lastName}}</h4>
                                <span>Member Sincen {{ profile.dateInscrit | date('M') }} {{ profile.dateInscrit | date('Y') }}</span>
                                <p>

                                    <img src="{{ asset('images/products/'~ profile.imageName) }}" alt="">
                                </p>
                            </div>

                            <ul class="user-profile__navigation">
                                <li><a href="{{path('listlogement') }}"><img src="{{ asset('bundles/app/images/icon/icon-cart.png') }}" alt="">List Logements</a></li>
                                <li><a href="{{path('listreservation') }}"><img src="{{ asset('bundles/app/images/icon/icon-cart.png') }}" alt="">My Bookings</a></li>
                                <li ><a href="{{path('meslogements') }}"><img src="{{ asset('bundles/app/images/icon/icon-cart.png') }}" alt="">Mes Logements</a></li>

                                <li class="current" ><a href="{{path('profilehostguest') }}"><img src="{{ asset('bundles/app/images/icon/icon-user.png') }}" alt="">My profile</a></li>

                                <li><a href="{{path('review') }}"><img src="{{ asset('bundles/app/images/icon/icon-review.png') }}" alt="">My reviews</a></li>
                                <li><a href="{{path('setting') }}"><img src="{{ asset('bundles/app/images/icon/icon-setting.png') }}" alt="">Settings</a></li>
                                <li><a href="#"><img src="{{ asset('bundles/app/images/icon/icon-heart.png') }}" alt="">Wishlist</a></li>
                                <li><a href="#"><img src="{{ asset('bundles/app/images/icon/icon-back.png') }}" alt="">Sign out</a></li>
                            </ul>
                        </div>
                        <div class="col-md-9">

                            <div class="user-form">
                                <div class="row">
                                    <h3> Information of your Promo</h3>
                                </div>
                                <div class="row">
                                    <div class="col-md-4">

                                        {{ form_start(form)}}
                                        <div class="field-input">

                                            <label> New Equipement </label>
                                            {{ form_widget(form.euipement, {'attr': {'class': 'form-control','placeholder':'Sauna' }}) }}
                                        </div>

                                        <div class="field-input">

                                            <button class="awe-btn awe-btn-1 awe-btn-small">Add Facility</button>
                                        </div>
                                        {{ form_end(form) }}

                                    </div>
                                    <div class="col-md-8">
                                        <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                                            <thead>
                                            <tr>
                                                <th> Title</th>

                                                <th> Action</th>
                                            </tr>
                                            </thead>
                                            <tfoot>

                                            <tr>
                                                <th> Title</th>

                                                <th> Action</th>
                                            </tr>
                                            </tfoot>

                                            <tbody>
                                            {% for felicity in felicity %}

                                                <tr>
                                                    <td> {{ felicity.euipement }}</td>

                                                    <td>


                                                        <a href=""><button type="button" class="btn btn-warning" >Delete</button></a>

                                                    </td>

                                                </tr>

                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <!-- End Main -->

{% endblock %}
         {% block js %}
        <script type="text/javascript" src="{{ asset('jTable/jquery-2.1.4.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('jTable/jquery.dataTables.min.js') }}"></script>
        <script type="text/javascript">$(document).ready(function() {
                $('#example').DataTable();
            } );
        </script>
        {% endblock js %}

src/Gstay/guesthostBundle/Resources/views/Logement/LogementPortfolio.html.twig
{% extends 'base.html.twig' %}
{% block title %} Settings-Portfolio {% endblock %}
{% block body %}



    <!-- Wrap -->
    <div id="wrap">


    <!--Banner-->
    <section class="sub-banner">
        <!--Background-->
        <div class="bg-parallax bg-1"></div>
        <!--End Background-->
        <!-- Logo -->
        <div class="logo-banner text-center">
            <a href="" title="">

                <img src="{{ asset('bundles/app/images/logo-banner.png') }}" alt="">
            </a>
        </div>
        <!-- Logo -->
    </section>
    <!--End Banner-->

    <!-- Main -->
    <div class="main">
        <div class="container">
            <div class="main-cn element-page bg-white clearfix">
                <!--Breakcrumb-->
                <section class="breakcrumb-sc">
                    <ul class="breadcrumb arrow">
                        <li><a href=""><i class="fa fa-home"></i></a></li>
                        <li>Add Event</li>
                    </ul>
                </section>
                <!--End Breakcrumb-->

                <section class="user-profile">
                    <div class="row">

                        <div class="col-md-3">
                            <div class="user-profile__header">
                                <h4>{{ profile.firstName }}_{{ profile.lastName}}</h4>
                                <span>Member Sincen {{ profile.dateInscrit | date('M') }} {{ profile.dateInscrit | date('Y') }}</span>
                                <p>

                                    <img src="{{ asset('images/products/'~ profile.imageName) }}" alt="">
                                </p>
                            </div>

                            <ul class="user-profile__navigation">
                                <li><a href="{{path('listlogement') }}"><img src="{{ asset('bundles/app/images/icon/icon-cart.png') }}" alt="">List Logements</a></li>
                                <li><a href="{{path('listreservation') }}"><img src="{{ asset('bundles/app/images/icon/icon-cart.png') }}" alt="">My Bookings</a></li>
                                <li ><a href="{{path('meslogements') }}"><img src="{{ asset('bundles/app/images/icon/icon-cart.png') }}" alt="">Mes Logements</a></li>

                                <li class="current" ><a href="{{path('profilehostguest') }}"><img src="{{ asset('bundles/app/images/icon/icon-user.png') }}" alt="">My profile</a></li>

                                <li><a href="{{path('review') }}"><img src="{{ asset('bundles/app/images/icon/icon-review.png') }}" alt="">My reviews</a></li>
                                <li><a href="{{path('setting') }}"><img src="{{ asset('bundles/app/images/icon/icon-setting.png') }}" alt="">Settings</a></li>
                                <li><a href="#"><img src="{{ asset('bundles/app/images/icon/icon-heart.png') }}" alt="">Wishlist</a></li>
                                <li><a href="#"><img src="{{ asset('bundles/app/images/icon/icon-back.png') }}" alt="">Sign out</a></li>
                            </ul>
                        </div>
                        <div class="col-md-9">

                            <div class="user-form">
                                <div class="row">
                                    <h3> Information of your Promo</h3>
                                </div>
                                <div class="row">
                                    <div class="col-md-4">

                                        {{ form_start(form)}}
                                        <div class="field-input">
                                            <label> Description</label>
                                            {{ form_widget(form.description, {'attr': {'class': 'ckeditor' }}) }}

                                        </div>
                                         <div class="field-input">
                                            {{ form_widget(form.imageFile) }}


                                        </div>


                                         <div class="field-input">
                                            {{ form_widget(form.ADD, {'attr': {'class': 'awe-btn awe-btn-1 awe-btn-medium' }}) }}


                                        </div>
                                        {{ form_end(form) }}

                                    </div>
                                    <div class="col-md-8">
                                        <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                                            <thead>
                                            <tr>

                                                 <th>image</th>
                                                 <th>descriptin
                                                 </th>
                                                <th> Action</th>
                                            </tr>
                                            </thead>
                                            <tfoot>

                                            <tr>

                                                <th>image</th>
                                                <th>description</th>

                                                <th> Action</th>
                                            </tr>
                                            </tfoot>

                                            <tbody>
                                            {% for logmentportfolios in LogemntPortfolio %}

                                                <tr>

                                                    <td> <img src="{{ asset('images/products/'~ logmentportfolios.imageName) }}" alt=""></td>

                                                           <td> {{ logmentportfolios.description }}</td>
                                                    <td>


                                                        <a href="{{ path('deletelogementPortfolio',{'id':logmentportfolios.id }) }}"><button type="button" class="btn btn-warning" >Delete</button></a>

                                                    </td>

                                                </tr>

                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <!-- End Main -->

{% endblock %}
         {% block js %}
        <script type="text/javascript" src="{{ asset('jTable/jquery-2.1.4.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('jTable/jquery.dataTables.min.js') }}"></script>
        <script type="text/javascript">$(document).ready(function() {
                $('#example').DataTable();
            } );
        </script>
        {% endblock js %}

src/Gstay/guesthostBundle/Resources/views/Logement/test.html.twig
{% for logement in logements %}

    {% if  logement.idlogementuser  ==  profile.id  %}


        MYHOUSE



    {% else %}
        <a href="{{ path('addreservation',{'idLogement':logements.idlogement }) }}" title="" class="awe-btn awe-btn-1 awe-btn-lager">ADD TO MY LOGEMENT</a>

    {% endif %}
{%  endfor %}