src/Gstay/carBundle/Entity/Cabine.php
<?php
/**
 * Created by PhpStorm.
 * User: Zarkouna
 * Date: 03/02/2017
 * Time: 22:10
 */

namespace Gstay\carBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;




use Vich\UploaderBundle\Mapping\Annotation as Vich;


/**
 * @ORM\Entity
 * @Vich\Uploadable
 */
class Cabine
{
    /**
 * @ORM\GeneratedValue
 * @ORM\Id
 * @ORM\Column(type="integer")
 */
    private $id ;
    /**
     * @ORM\ManyToOne(targetEntity="Croisiere",inversedBy="Cabine")
     * @ORM\JoinColumn(name="id_croisiere", referencedColumnName="id")
     */
    public $id_croisiere;

    /**
     * @return mixed
     */
    public function getIdCroisiere()
    {
        return $this->id_croisiere;
    }

    /**
     * @param mixed $id_croisiere
     */
    public function setIdCroisiere($id_croisiere)
    {
        $this->id_croisiere = $id_croisiere;
    }
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $nom ;
    /**
     * @ORM\Column(type="string",length=255)
     */
    private $type ;

    /**
     * @return mixed
     */
    public function getQuantite()
    {
        return $this->quantite;
    }

    /**
     * @param mixed $quantite
     */
    public function setQuantite($quantite)
    {
        $this->quantite = $quantite;
    }
    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $quantite ;
    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $superficie ;
    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $maxper ;
    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $nbr_lit ;
    /**
     * @ORM\Column(type="boolean")
     */
    private $salle_bain ;
    /**
     * @ORM\Column(type="boolean")
     */
    private $tele;
    /**
     * @ORM\Column(type="boolean")
     */
    private $mini_bar ;
    /**
     * @ORM\Column(type="boolean")
     */
    private $coffre_fort ;
    /**
     * @ORM\Column(type="boolean")
     */
    private $clim ;
    /**
     * @ORM\Column(type="boolean")
     */
    private $dressing ;

    /**
     * @return mixed
     */
    public function getPrix()
    {
        return $this->prix;
    }

    /**
     * @param mixed $prix
     */
    public function setPrix($prix)
    {
        $this->prix = $prix;
    }
    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getIdNavire()
    {
        return $this->id_navire;
    }

    /**
     * @param mixed $id_navire
     */
    public function setIdNavire($id_navire)
    {
        $this->id_navire = $id_navire;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     */
    public function setType($type)
    {
        $this->type = $type;
    }

    /**
     * @return mixed
     */
    public function getSuperficie()
    {
        return $this->superficie;
    }

    /**
     * @param mixed $superficie
     */
    public function setSuperficie($superficie)
    {
        $this->superficie = $superficie;
    }

    /**
     * @return mixed
     */
    public function getMaxper()
    {
        return $this->maxper;
    }

    /**
     * @param mixed $maxper
     */
    public function setMaxper($maxper)
    {
        $this->maxper = $maxper;
    }

    /**
     * @return mixed
     */
    public function getNbrLit()
    {
        return $this->nbr_lit;
    }

    /**
     * @param mixed $nbr_lit
     */
    public function setNbrLit($nbr_lit)
    {
        $this->nbr_lit = $nbr_lit;
    }

    /**
     * @return mixed
     */
    public function getSalleBain()
    {
        return $this->salle_bain;
    }

    /**
     * @param mixed $salle_bain
     */
    public function setSalleBain($salle_bain)
    {
        $this->salle_bain = $salle_bain;
    }

    /**
     * @return mixed
     */
    public function getTele()
    {
        return $this->tele;
    }

    /**
     * @param mixed $tele
     */
    public function setTele($tele)
    {
        $this->tele = $tele;
    }

    /**
     * @return mixed
     */
    public function getMiniBar()
    {
        return $this->mini_bar;
    }

    /**
     * @param mixed $mini_bar
     */
    public function setMiniBar($mini_bar)
    {
        $this->mini_bar = $mini_bar;
    }

    /**
     * @return mixed
     */
    public function getCoffreFort()
    {
        return $this->coffre_fort;
    }

    /**
     * @param mixed $coffre_fort
     */
    public function setCoffreFort($coffre_fort)
    {
        $this->coffre_fort = $coffre_fort;
    }

    /**
     * @return mixed
     */
    public function getClim()
    {
        return $this->clim;
    }

    /**
     * @param mixed $clim
     */
    public function setClim($clim)
    {
        $this->clim = $clim;
    }

    /**
     * @return mixed
     */
    public function getDressing()
    {
        return $this->dressing;
    }

    /**
     * @param mixed $dressing
     */
    public function setDressing($dressing)
    {
        $this->dressing = $dressing;
    }

    /**
     * @return mixed
     */

    /**
     * @return mixed
     */
    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="imageName")
     *
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     *
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return Cabine
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param string $imageName
     *
     * @return Cabine
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;


        return $this;
    }

    /**
     * @return string|null
     */
    public function getImageName()
    {
        return $this->imageName;
    }

}

src/Gstay/carBundle/Entity/Navire.php
<?php
namespace Gstay\carBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Created by PhpStorm.
 * User: Zarkouna
 * Date: 02/02/2017
 * Time: 21:57
 */
/**
 * @ORM\Entity
 * @Vich\Uploadable
 */
class Navire
{
/**
* @ORM\GeneratedValue
* @ORM\Id
* @ORM\Column(type="integer")
*/
private $id ;

    /**
     * @ORM\ManyToOne(targetEntity="ProfileCroisiere", inversedBy="Navire")
     * @ORM\JoinColumn(name="id_userCruiser", referencedColumnName="id")
     */
    private $id_profile ;



    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getIdProfile()
    {
        return $this->id_profile;
    }

    /**
     * @param mixed $id_profile
     */
    public function setIdProfile($id_profile)
    {
        $this->id_profile = $id_profile;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getMiseService()
    {
        return $this->mise_service;
    }

    /**
     * @param mixed $mise_service
     */
    public function setMiseService($mise_service)
    {
        $this->mise_service = $mise_service;
    }

    /**
     * @return mixed
     */
    public function getRenove()
    {
        return $this->renove;
    }

    /**
     * @param mixed $renove
     */
    public function setRenove($renove)
    {
        $this->renove = $renove;
    }

    /**
     * @return mixed
     */
    public function getLongueur()
    {
        return $this->longueur;
    }

    /**
     * @param mixed $longueur
     */
    public function setLongueur($longueur)
    {
        $this->longueur = $longueur;
    }

    /**
     * @return mixed
     */
    public function getTirant()
    {
        return $this->tirant;
    }

    /**
     * @param mixed $tirant
     */
    public function setTirant($tirant)
    {
        $this->tirant = $tirant;
    }

    /**
     * @return mixed
     */
    public function getTonnage()
    {
        return $this->tonnage;
    }

    /**
     * @param mixed $tonnage
     */
    public function setTonnage($tonnage)
    {
        $this->tonnage = $tonnage;
    }

    /**
     * @return mixed
     */
    public function getVitesse()
    {
        return $this->vitesse;
    }

    /**
     * @param mixed $vitesse
     */
    public function setVitesse($vitesse)
    {
        $this->vitesse = $vitesse;
    }

    /**
     * @return mixed
     */
    public function getNbrPont()
    {
        return $this->nbr_pont;
    }

    /**
     * @param mixed $nbr_pont
     */
    public function setNbrPont($nbr_pont)
    {
        $this->nbr_pont = $nbr_pont;
    }

    /**
     * @return mixed
     */
    public function getCapacite()
    {
        return $this->capacite;
    }

    /**
     * @param mixed $capacite
     */
    public function setCapacite($capacite)
    {
        $this->capacite = $capacite;
    }

    /**
     * @return mixed
     */
    public function getEquipage()
    {
        return $this->equipage;
    }

    /**
     * @param mixed $equipage
     */
    public function setEquipage($equipage)
    {
        $this->equipage = $equipage;
    }

    /**
     * @return mixed
     */
    public function getLangue()
    {
        return $this->langue;
    }

    /**
     * @param mixed $langue
     */
    public function setLangue($langue)
    {
        $this->langue = $langue;
    }

    /**
     * @return mixed
     */
    public function getMonnaies()
    {
        return $this->monnaies;
    }

    /**
     * @param mixed $monnaies
     */
    public function setMonnaies($monnaies)
    {
        $this->monnaies = $monnaies;
    }

    /**
     * @return mixed
     */
    public function getInternet()
    {
        return $this->internet;
    }

    /**
     * @param mixed $internet
     */
    public function setInternet($internet)
    {
        $this->internet = $internet;
    }

    /**
     * @return mixed
     */
    public function getCabines()
    {
        return $this->cabines;
    }

    /**
     * @param mixed $cabines
     */
    public function setCabines($cabines)
    {
        $this->cabines = $cabines;
    }

    /**
     * @return mixed
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * @param mixed $service
     */
    public function setService($service)
    {
        $this->service = $service;
    }

    /**
     * @return mixed
     */
    public function getDivertis()
    {
        return $this->divertis;
    }

    /**
     * @param mixed $divertis
     */
    public function setDivertis($divertis)
    {
        $this->divertis = $divertis;
    }

    /**
     * @return mixed
     */
    public function getFitness()
    {
        return $this->fitness;
    }

    /**
     * @param mixed $fitness
     */
    public function setFitness($fitness)
    {
        $this->fitness = $fitness;
    }

    /**
     * @return mixed
     */
    public function getShopping()
    {
        return $this->shopping;
    }

    /**
     * @param mixed $shopping
     */
    public function setShopping($shopping)
    {
        $this->shopping = $shopping;
    }

    /**
     * @return mixed
     */
    public function getFamille()
    {
        return $this->famille;
    }

    /**
     * @param mixed $famille
     */
    public function setFamille($famille)
    {
        $this->famille = $famille;
    }

    /**
     * @return mixed
     */
    public function getTenue()
    {
        return $this->tenue;
    }

    /**
     * @param mixed $tenue
     */
    public function setTenue($tenue)
    {
        $this->tenue = $tenue;
    }

    /**
     * @return string
     */

    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $nom ;
    /**
     * @ORM\Column(type="date")
     */
    private $mise_service ;
    /**
     * @ORM\Column(type="date")
     */
    private $renove ;
    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $longueur ;
    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $tirant ;
    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $tonnage ;
    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $vitesse ;
    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $nbr_pont ;
    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $capacite ;
    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $equipage ;
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $langue ;
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $monnaies ;
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $internet ;
    /**
 * @ORM\Column(type="text",length=65000,nullable=true)
 */
    private $cabines ;
    /**
     * @ORM\Column(type="text",length=65000,nullable=true)
     */
    private $service ;
    /**
     * @ORM\Column(type="text",length=65000,nullable=true)
     */
    private $divertis;
    /**
     * @ORM\Column(type="text",length=65000,nullable=true)
     */
    private $fitness ;
    /**
     * @ORM\Column(type="text",length=65000,nullable=true)
     */
    private $shopping ;
    /**
     * @ORM\Column(type="text",length=65000,nullable=true)
     */
    private $famille ;
    /**
     * @ORM\Column(type="text",length=65000,nullable=true)
     */
    private $tenue ;
    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="imageName")
     *
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return Navire
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param string $imageName
     *
     * @return Navire
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;


        return $this;
    }

    /**
     * @return string|null
     */
    public function getImageName()
    {
        return $this->imageName;
    }




}

src/Gstay/carBundle/Resources/views/front/details_cabine.html.twig
{% extends 'base.html.twig' %}
{% block title %} add promo {% endblock %}
{% block body %}






























    <div class="main main-dt">

    <div class="container">
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Get a ticket for {{ cabine.nom }} </h4>
                </div>
                <div class="modal-body">
                    {% if app.user %}
                        <p>welcome !!</p>
                        <form class="controleticket">





                            <input value="{{ app.user.id }} " type="text" name="iduser" hidden>
                            <input  value="{{ cabine.id }} " type="text" name="idtour" hidden>
                            <input  value="{{ app.user.type }} " type="text" name="type" hidden>

                            <label >Email:</label>
                            <input class="form-control" value="{{ app.user.email }} " type="text" name="email" disabled>


                            <label >Nb tickets:</label>
                            <input class="form-control"  type="number" min="1" max="99" id="ticketnumber" name="nbticket" value="1" onchange="checknbticket({{ cabine.prix }},'{{ cabine.id }}')">
                            <p id="prixtotal" > Total price:  </p> <span  id="error" style="background-color: red"></span>
                            <p  > Reservation Key  </p> <span  id="keygen" ></span>
                            </li>
                            </ul>

                        </form>
                    {% else %}
                        <p>You are not connected !!</p>
                        <div class="row">
                            <div class=" col-md-6">
                                <a href="{{ path('fos_user_security_login', { 'url': app.request.uri }) }}"> <button class="awe-btn-medium">Login</button></a>
                            </div>

                            <div class=" col-md-6">
                                <button class="awe-btn-medium">Sing up</button>
                            </div>

                        </div>

                    {% endif %}
                </div>
                <div class="modal-footer">
                    {% if app.user %}
                        <button  class="btn btn-success" id="getbtn" >Get </button>
                    {% endif %}
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>
    <div class="main-cn detail-page bg-white clearfix">

    <!-- Breakcrumb -->
    <section class="breakcrumb-sc">
        <ul class="breadcrumb arrow">
            <li><a href="index.html"><i class="fa fa-home"></i></a></li>
            <li><a href="hotel.html" title="">Cruises</a></li>
            <li><a href="#" title=""> {{ cabine.idCroisiere.idNavire.nom }}</a></li>

        </ul>
        <div class="support float-right">
            <small>Got a question?</small> {{ cabine.idCroisiere.idProfile.phoneNum }}
        </div>
    </section>
    <!-- End Breakcrumb -->

    <!-- Header Detail -->
    <section class="head-detail">
        <div class="head-dt-cn">
            <div class="row">
                <div class="col-sm-7">
                    <h1>{{ cabine.idCroisiere.nom }}</h1>
                    <ul>
                        <li>Ship: {{ cabine.idCroisiere.idNavire.nom }}</li>
                        <li> {{ cabine.idCroisiere.idProfile.nomCompa }}
                            {% if (cabine.idCroisiere.idProfile.stars == 4) %} <!--no star-->
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>
                            {% elseif (cabine.idCroisiere.idProfile.stars) == 3 %}<!--one star-->
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>
                            {% elseif (cabine.idCroisiere.idProfile.stars) == 2 %}<!--one star-->
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>
                            {% elseif (cabine.idCroisiere.idProfile.stars) == 1 %}<!--one star-->
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>
                            {% elseif (cabine.idCroisiere.idProfile.stars) == 5 %}<!--one star-->
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>
                                <i class="fa fa-star" style ="color:#FFD700" aria-hidden="true"></i>


                            {% endif %}
                        </li>

                    </ul>
                </div>
                <div class="col-sm-5 text-right">
                    <p class="price-book">
                        <span>{{ cabine.prix }} €</span>
                        <a href="" title="" class="awe-btn awe-btn-1 awe-btn-lager" data-toggle="modal" data-target="#myModal">Book now</a>
                        <a href="{{ path('show_cruisePDF',{'id':cabine.id}) }}"class="awe-btn awe-btn-1 awe-btn-lager">Download PDF</a>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <div class="payment-room">
        <div class="row">
            <div class="col-lg-6">
                <div class="payment-info">
                    <h2>{{ cabine.nom }} : {{ cabine.type }} </h2>
                    <span class="star-room">
                                        <i class="glyphicon glyphicon-star"></i>
                                        <i class="glyphicon glyphicon-star"></i>
                                        <i class="glyphicon glyphicon-star"></i>
                                        <i class="glyphicon glyphicon-star"></i>
                                        <i class="glyphicon glyphicon-star"></i>
                                    </span>
                    <ul>
                        <li>
                            <span>Cabine Type:</span>
                            {{ cabine.type }}
                        </li>
                        <li>
                            <span>Area:</span>
                            {{ cabine.superficie }}
                            m²
                        </li>
                        <li>
                            <span>Maximum number of people:</span>&nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;

                            {{ cabine.maxper }}
                        </li>
                        <li>
                            <span>Number of beds:</span>&nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;
                            &nbsp;

                            {{ cabine.nbrLit }}
                        </li>
                        <li>
                            <span>Quantity:</span>
                            {{ cabine.quantite }}
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="payment-price">

                    <figure>
                        <img style="max-height: 100px;" src="{{ asset('images/products/'~cabine.imageName) }}" alt="">
                    </figure>
                    <div class="total-trip">

                        Bathroom with shower:{{ cabine.salleBain }}<br>
                        Television: {{ cabine.tele }}<br>
                        Minibar:{{ cabine.miniBar }}<br>
                        Safety Deposit Box:{{ cabine.coffreFort }}<br>
                        Air conditioner:{{ cabine.clim }}<br>
                        spacious dressing:{{ cabine.dressing }}<br>

                        <p>
                            Trip Total: <ins>600€</ins>

                            <i>Cruise tax 7% not included, Service charge 10% not included
                            </i>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    <script src="{{ asset('lobibox-master/lib/jquery.1.11.min.js') }}"> </script>



    <script>
        $(function() {
//twitter bootstrap script
            $("#getbtn").click(function(){

                $.ajax({
                    type: "POST",
                    url: "{{ asset('ajax/modaltour1/getticket.php') }}",
                    data: $('form.controleticket').serialize(),
                    success: function(msg){
                    alert(msg);
                        document.getElementById('keygen').innerHTML=msg;
                        Lobibox.notify('success', {
                            size: 'large',
                            msg: '  please check your email to get your ticket . thank you for choosing us  '
                        });
                        $('#myModal').close();

                        document.getElementById('ticketnumber').value=1;
                        document.getElementById('prixtotal').innerHTML ="";

                    },
                    error: function(){
                        alert("failure");
                    }
                });
            });
        });
    </script>
    <script >



        function checknbticket(x,idtour) {

            var nb = document.getElementById('ticketnumber').value;
            var prixtotal = nb * x ;
            document.getElementById('prixtotal').innerHTML = "Total price: "+prixtotal+" DT "  ;

            var khaled = new XMLHttpRequest();
            khaled.open("get","{{ asset('ajax/zcheck.php?nb') }}="+nb+"&idtour="+idtour,true);
            khaled.send() // avec le GET  les parametre sont vides ;
            khaled.onreadystatechange = function result()
            {
                document.getElementById("error").innerHTML= khaled.responseText;



            }
            var error = document.getElementById('error').innerHTML;
            if(error.length > 0 )
            {
                document.getElementById('getbtn').setAttribute('disabled','disabled');

            }else {
                document.getElementById('getbtn').removeAttribute("disabled");
            }



        }






    </script>
{% endblock %}