src/Gstay/carBundle/Entity/Navire.php
<?php
namespace Gstay\carBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Created by PhpStorm.
 * User: Zarkouna
 * Date: 02/02/2017
 * Time: 21:57
 */
/**
 * @ORM\Entity
 * @Vich\Uploadable
 */
class Navire
{
/**
* @ORM\GeneratedValue
* @ORM\Id
* @ORM\Column(type="integer")
*/
private $id ;

    /**
     * @ORM\ManyToOne(targetEntity="ProfileCroisiere", inversedBy="Navire")
     * @ORM\JoinColumn(name="id_userCruiser", referencedColumnName="id")
     */
    private $id_profile ;



    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getIdProfile()
    {
        return $this->id_profile;
    }

    /**
     * @param mixed $id_profile
     */
    public function setIdProfile($id_profile)
    {
        $this->id_profile = $id_profile;
    }

    /**
     * @return mixed
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param mixed $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return mixed
     */
    public function getMiseService()
    {
        return $this->mise_service;
    }

    /**
     * @param mixed $mise_service
     */
    public function setMiseService($mise_service)
    {
        $this->mise_service = $mise_service;
    }

    /**
     * @return mixed
     */
    public function getRenove()
    {
        return $this->renove;
    }

    /**
     * @param mixed $renove
     */
    public function setRenove($renove)
    {
        $this->renove = $renove;
    }

    /**
     * @return mixed
     */
    public function getLongueur()
    {
        return $this->longueur;
    }

    /**
     * @param mixed $longueur
     */
    public function setLongueur($longueur)
    {
        $this->longueur = $longueur;
    }

    /**
     * @return mixed
     */
    public function getTirant()
    {
        return $this->tirant;
    }

    /**
     * @param mixed $tirant
     */
    public function setTirant($tirant)
    {
        $this->tirant = $tirant;
    }

    /**
     * @return mixed
     */
    public function getTonnage()
    {
        return $this->tonnage;
    }

    /**
     * @param mixed $tonnage
     */
    public function setTonnage($tonnage)
    {
        $this->tonnage = $tonnage;
    }

    /**
     * @return mixed
     */
    public function getVitesse()
    {
        return $this->vitesse;
    }

    /**
     * @param mixed $vitesse
     */
    public function setVitesse($vitesse)
    {
        $this->vitesse = $vitesse;
    }

    /**
     * @return mixed
     */
    public function getNbrPont()
    {
        return $this->nbr_pont;
    }

    /**
     * @param mixed $nbr_pont
     */
    public function setNbrPont($nbr_pont)
    {
        $this->nbr_pont = $nbr_pont;
    }

    /**
     * @return mixed
     */
    public function getCapacite()
    {
        return $this->capacite;
    }

    /**
     * @param mixed $capacite
     */
    public function setCapacite($capacite)
    {
        $this->capacite = $capacite;
    }

    /**
     * @return mixed
     */
    public function getEquipage()
    {
        return $this->equipage;
    }

    /**
     * @param mixed $equipage
     */
    public function setEquipage($equipage)
    {
        $this->equipage = $equipage;
    }

    /**
     * @return mixed
     */
    public function getLangue()
    {
        return $this->langue;
    }

    /**
     * @param mixed $langue
     */
    public function setLangue($langue)
    {
        $this->langue = $langue;
    }

    /**
     * @return mixed
     */
    public function getMonnaies()
    {
        return $this->monnaies;
    }

    /**
     * @param mixed $monnaies
     */
    public function setMonnaies($monnaies)
    {
        $this->monnaies = $monnaies;
    }

    /**
     * @return mixed
     */
    public function getInternet()
    {
        return $this->internet;
    }

    /**
     * @param mixed $internet
     */
    public function setInternet($internet)
    {
        $this->internet = $internet;
    }

    /**
     * @return mixed
     */
    public function getCabines()
    {
        return $this->cabines;
    }

    /**
     * @param mixed $cabines
     */
    public function setCabines($cabines)
    {
        $this->cabines = $cabines;
    }

    /**
     * @return mixed
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * @param mixed $service
     */
    public function setService($service)
    {
        $this->service = $service;
    }

    /**
     * @return mixed
     */
    public function getDivertis()
    {
        return $this->divertis;
    }

    /**
     * @param mixed $divertis
     */
    public function setDivertis($divertis)
    {
        $this->divertis = $divertis;
    }

    /**
     * @return mixed
     */
    public function getFitness()
    {
        return $this->fitness;
    }

    /**
     * @param mixed $fitness
     */
    public function setFitness($fitness)
    {
        $this->fitness = $fitness;
    }

    /**
     * @return mixed
     */
    public function getShopping()
    {
        return $this->shopping;
    }

    /**
     * @param mixed $shopping
     */
    public function setShopping($shopping)
    {
        $this->shopping = $shopping;
    }

    /**
     * @return mixed
     */
    public function getFamille()
    {
        return $this->famille;
    }

    /**
     * @param mixed $famille
     */
    public function setFamille($famille)
    {
        $this->famille = $famille;
    }

    /**
     * @return mixed
     */
    public function getTenue()
    {
        return $this->tenue;
    }

    /**
     * @param mixed $tenue
     */
    public function setTenue($tenue)
    {
        $this->tenue = $tenue;
    }

    /**
     * @return string
     */

    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $nom ;
    /**
     * @ORM\Column(type="date")
     */
    private $mise_service ;
    /**
     * @ORM\Column(type="date")
     */
    private $renove ;
    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $longueur ;
    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $tirant ;
    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $tonnage ;
    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $vitesse ;
    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $nbr_pont ;
    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $capacite ;
    /**
     * @ORM\Column(type="integer",nullable=true)
     */
    private $equipage ;
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $langue ;
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $monnaies ;
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $internet ;
    /**
 * @ORM\Column(type="text",length=65000,nullable=true)
 */
    private $cabines ;
    /**
     * @ORM\Column(type="text",length=65000,nullable=true)
     */
    private $service ;
    /**
     * @ORM\Column(type="text",length=65000,nullable=true)
     */
    private $divertis;
    /**
     * @ORM\Column(type="text",length=65000,nullable=true)
     */
    private $fitness ;
    /**
     * @ORM\Column(type="text",length=65000,nullable=true)
     */
    private $shopping ;
    /**
     * @ORM\Column(type="text",length=65000,nullable=true)
     */
    private $famille ;
    /**
     * @ORM\Column(type="text",length=65000,nullable=true)
     */
    private $tenue ;
    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="imageName")
     *
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return Navire
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param string $imageName
     *
     * @return Navire
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;


        return $this;
    }

    /**
     * @return string|null
     */
    public function getImageName()
    {
        return $this->imageName;
    }




}

src/Gstay/carBundle/Entity/ProfileCroisiere.php
<?php
/**
 * Created by PhpStorm.
 * User: Zarkouna
 * Date: 04/02/2017
 * Time: 21:20
 */

namespace Gstay\carBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Created by PhpStorm.
 * User: Zarkouna
 * Date: 02/02/2017
 * Time: 21:57
 */
/**
 * @ORM\Entity
 * @Vich\Uploadable
 */
class ProfileCroisiere
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue
     */
    private $id ;

    /**
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\User")
     * @ORM\JoinColumn(name="id_user", referencedColumnName="id")
     */
    private $id_user ;

    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $nom_compa;

    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $mat_fisc;
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $activite;

    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $post_comp;
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $first_name;
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $last_name;

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->first_name;
    }

    /**
     * @param mixed $first_name
     */
    public function setFirstName($first_name)
    {
        $this->first_name = $first_name;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->last_name;
    }

    /**
     * @param mixed $last_name
     */
    public function setLastName($last_name)
    {
        $this->last_name = $last_name;
    }

    /**
     * @return mixed
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * @param mixed $country
     */
    public function setCountry($country)
    {
        $this->country = $country;
    }

    /**
     * @return mixed
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * @param mixed $state
     */
    public function setState($state)
    {
        $this->state = $state;
    }

    /**
     * @return mixed
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param mixed $city
     */
    public function setCity($city)
    {
        $this->city = $city;
    }

    /**
     * @return mixed
     */
    public function getStreetAdresse()
    {
        return $this->street_adresse;
    }

    /**
     * @param mixed $street_adresse
     */
    public function setStreetAdresse($street_adresse)
    {
        $this->street_adresse = $street_adresse;
    }

    /**
     * @return mixed
     */
    public function getPhoneNum()
    {
        return $this->phone_num;
    }

    /**
     * @param mixed $phone_num
     */
    public function setPhoneNum($phone_num)
    {
        $this->phone_num = $phone_num;
    }

    /**
     * @return mixed
     */
    public function getFax()
    {
        return $this->fax;
    }

    /**
     * @param mixed $fax
     */
    public function setFax($fax)
    {
        $this->fax = $fax;
    }
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */

    private $country;
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $state;
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $city;


    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $street_adresse;
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $phone_num;
    /**
     * @ORM\Column(type="string",length=255,nullable=true)
     */
    private $fax;
    /**
     * @ORM\Column(type="float",nullable=true)
     */
    private $stars;


    /**
     * @return mixed
     */
    public function getStars()
    {
        return $this->stars;
    }

    /**
     * @param mixed $stars
     */
    public function setStars($stars)
    {
        $this->stars = $stars;
    }


    /**
     * @ORM\Column(type="date",nullable=true)
     */
    private $dateInscrit;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getIdUser()
    {
        return $this->id_user;
    }

    /**
     * @param mixed $id_user
     */
    public function setIdUser($id_user)
    {
        $this->id_user = $id_user;
    }

    /**
     * @return mixed
     */
    public function getNomCompa()
    {
        return $this->nom_compa;
    }

    /**
     * @param mixed $nom_compa
     */
    public function setNomCompa($nom_compa)
    {
        $this->nom_compa = $nom_compa;
    }

    /**
     * @return mixed
     */
    public function getMatFisc()
    {
        return $this->mat_fisc;
    }

    /**
     * @param mixed $mat_fisc
     */
    public function setMatFisc($mat_fisc)
    {
        $this->mat_fisc = $mat_fisc;
    }

    /**
     * @return mixed
     */
    public function getActivite()
    {
        return $this->activite;
    }

    /**
     * @param mixed $activite
     */
    public function setActivite($activite)
    {
        $this->activite = $activite;
    }

    /**
     * @return mixed
     */
    public function getPostComp()
    {
        return $this->post_comp;
    }

    /**
     * @param mixed $post_comp
     */
    public function setPostComp($post_comp)
    {
        $this->post_comp = $post_comp;
    }

    /**
     * @return mixed
     */
    public function getDateInscrit()
    {
        return $this->dateInscrit;
    }

    /**
     * @param mixed $dateInscrit
     */
    public function setDateInscrit($dateInscrit)
    {
        $this->dateInscrit = $dateInscrit;
    }
    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="imageName")
     *
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     *
     * @var string
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     *
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the  update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return ProfileCroisiere
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }

       return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param string $imageName
     *
     * @return ProfileCroisiere
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;


        return $this;
    }

    /**
     * @return string|null
     */
    public function getImageName()
    {
        return $this->imageName;
    }
}

src/Gstay/carBundle/Resources/views/Ship/show_ship.html.twig
{% extends 'base.html.twig' %}
{% block title %} Manage Promos {% endblock %}
{% block body %}

    <link href="{{ asset('jTable/jquery.dataTables.min.css') }}" rel="stylesheet" type="text/css" />

    <!-- Wrap -->
    <!-- Wrap -->


    <!--Banner-->
    <section class="sub-banner">
        <!--Background-->
        <div class="bg-parallax bg-1"></div>
        <!--End Background-->
        <!-- Logo -->
        <div class="logo-banner text-center">
            <a href="" title="">

                <img src=" {{ asset('bundles/app/images/logo-banner.png') }}" >
            </a>
        </div>
        <!-- Logo -->
    </section>
    <!--End Banner-->

    <!-- Main -->
    <div class="main">
        <div class="container">
            <div class="main-cn element-page bg-white clearfix">
                <!--Breakcrumb-->
                <section class="breakcrumb-sc">
                    <ul class="breadcrumb arrow">
                        <li><a href="index.html"><i class="fa fa-home"></i></a></li>
                        <li>My Ships</li>
                    </ul>
                </section>
                <!--End Breakcrumb-->

                <section class="user-profile">
                    <div class="row">
                        <div class="col-md-3">
                            <div class="user-profile__header">
                                <h4>{{ ProfileCroisiere.nomCompa}}_{{ ProfileCroisiere.nomCompa }}</h4>
                                <span>Member Sincen {{ ProfileCroisiere.dateInscrit | date('M') }} {{ ProfileCroisiere.dateInscrit | date('Y') }}</span>
                                <p>

                                    <img src="{{ asset('images/products/'~ProfileCroisiere.imageName) }}" alt="">
                                </p>
                            </div>

                            <ul class="user-profile__navigation">
                                <li><a href=""><img src="{{ asset('bundles/app/images/icon/icon-cart.png') }}" alt="">Bookings</a></li>
                                <li ><a href="{{ path('cruiser_profile') }}"><img src="{{ asset('bundles/app/images/icon/icon-user.png') }}" alt="">My profile</a></li>
                                <li class="current"><a href="{{ path('show_ship') }}"><img src="{{ asset('bundles/app/images/icon/icon-review.png') }}" alt="">My Ships</a></li>
                                <li><a href="{{ path('show_cruise') }}"><img src="{{ asset('bundles/app/images/icon/icon-setting.png') }}" alt="">My Cruises</a></li>
                                <li ><a href="{{ path('cruise_pictures') }}"><img src="{{ asset('bundles/app/images/icon/icon-heart.png') }}" alt="">Pictures</a></li>
                                <li><a href="{{ path('fos_user_security_logout') }}"><img src="{{ asset('bundles/app/images/icon/icon-back.png') }}" alt="">Sign out</a></li>
                            </ul>
                        </div>
                        <div class="col-md-9">

                            <div class="user-form">
                                <div class="row">
                                    <div class="col-md-12">
                                        <h3>Manage Ships</h3>
                                        {% if    app.request.get('msg')  and  msg != "" %}
                                        <div class="alert alert-success">
                                            <strong>Well done!</strong>

                                            {{ app.request.get('msg') }}
                                        </div>
                                         {% endif %}





                                        <div class="field-input">
                                            <a href="{{ path('add_ship') }}">
                                            <button  class="awe-btn awe-btn-1 awe-btn-medium">Add New Ship </button>
                                            </a>
                                        </div>




                                         <br>
                                          <br>
                                           <br>

                                        <table id="example" class="table table-striped table-bordered table-hover" cellspacing="0" width="100%">
                                            <thead>
                                         <tr>
                                             <th> Ship Name</th>
                                             <th> Commissioning of the boat</th>

                                             <th> Crew members</th>
                                             <th> Accommodation capacity </th>
                                             <th> Action</th>
                                         </tr>
                                         </thead>
                                            <tfoot>

                                            <tr>
                                                <th> Ship Name</th>
                                             <th> Commissioning of the boat</th>

                                             <th> Crew members</th>
                                             <th> Accommodation capacity </th>
                                             <th> Action</th>
                                            </tr>
                                            </tfoot>

                                            <tbody>
                                        {% for Navire in Navire %}

                                            <tr>
                                                <td> {{ Navire.nom }}</td>
                                                <td> {{ Navire.miseService | date('y/m/d') }}</td>

                                                <td> {{ Navire.equipage }} </td>
                                                <td> {{ Navire.capacite }} </td>
                                                <td>

                                                <a href="{{ path('edit_ship',{'nom': Navire.nom}) }}"><button type="button" class="btn btn-primary" >Edit</button></a>
                                                 &nbsp;

                                                   <a href="{{ path('delete_ship',{'id': Navire.id}) }}"><button type="button" class="btn btn-danger" >Delete</button></a>


                                                </br>

                                            </tr>

                                        {% endfor %}
                                            </tbody>
                        </table>
                                     </div>
                                 </div>
                             </div>
                         </div>
                </section>
            </div>
        </div>
    </div>
    <!-- End Main -->


{% endblock %}

        {% block js %}
        <script type="text/javascript" src="{{ asset('jTable/jquery-2.1.4.min.js') }}"></script>
        <script type="text/javascript" src="{{ asset('jTable/jquery.dataTables.min.js') }}"></script>
        <script type="text/javascript">$(document).ready(function() {
                $('#example').DataTable();
            } );
        </script>
        {% endblock js %}